### ISSUE TITLE
not able to pass arguments

### ISSUE THREAD

**Issue by programmerq** [docker/v1.10-migrator#4]
I tried to run the migrator and got this error:

```
$ docker run --rm -v /var/lib/docker:/var/lib/docker docker/v1.10-migrator
time="2016-02-04T21:14:15Z" level=fatal msg="multiple storage drivers found at /var/lib/docker, please specify one with \"-d\" option"
```

So I decided to follow the advice, but I got the same error:

```
$ docker run --rm -v /var/lib/docker:/var/lib/docker docker/v1.10-migrator -d aufs
time="2016-02-04T21:14:15Z" level=fatal msg="multiple storage drivers found at /var/lib/docker, please specify one with \"-d\" option"
```

Looking at the image, it looks like the entrypoint is set as:

```
    "Entrypoint": [
        "/bin/sh",
        "-c",
        "/bin/v1.10-migrator"
    ],
```

I then tried overriding the entrypoint to call `/bin/v1.10-migrator` directly:

```
$ docker run --rm --entrypoint /bin/v1.10-migrator -v /var/lib/docker:/var/lib/docker dock
er/v1.10-migrator -d aufs
flag provided but not defined: -d
Usage of /bin/v1.10-migrator:
  -g string
        Docker root dir (default "/var/lib/docker")
  -s string
        Storage driver to migrate (default "auto")
```

Whoops, looks like I need to use `-s` instead of `-d`

This is using `docker/v1.10-migrator                          latest              dce7e318b173        2 weeks ago         11.97 MB` as of today (digest `sha256:bd2b245d5d22dd94ec4a8417a9b81bb5e90b171031c6e216484db3fe300c2097`)

Two issues I guess: change help string to agree with the argument that is needed, and change the entrypoint to not shell encapsulate `/bin/v1.10-migrator` so options I pass in as the CMD get interpreted.

**Comment by tonistiigi** [comment]
Thanks for the report.

**Comment by icecrime** [comment]
I just repushed the image to https://hub.docker.com/r/docker/v1.10-migrator/.

Thanks!

**Comment by programmerq** [comment]
Awesome! Thanks for the quick response!
